START TRANSACTION;

ALTER TABLE `ma_sys_message` ADD COLUMN `message_uuid` VARCHAR(50) NULL DEFAULT NULL COMMENT '消息uuid';
ALTER TABLE `ma_sys_message` ADD COLUMN `deleted_at` BIGINT(20) NULL DEFAULT NULL COMMENT '删除时间';
ALTER TABLE `ma_sys_message` MODIFY COLUMN `type` VARCHAR(20) NULL DEFAULT NULL COMMENT '消息类型参考枚举类';
ALTER TABLE `ma_sys_notice` ADD COLUMN `uuid` VARCHAR(50) NULL DEFAULT NULL COMMENT 'uuid';

COMMIT;


