<?php
/**
 *+------------------
 * madong
 *+------------------
 * Copyright (c) https://gitee.com/motion-code  All rights reserved.
 *+------------------
 * Author: Mr. April (405784684@qq.com)
 *+------------------
 * Official Website: http://www.madong.tech
 */

return [
    [
        'group_code'  => 'default',
        'name'        => '所属分组',
        'code'        => 'sys_dict_group_code',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '默认分组',
                'value'      => 'value1',
                'code'       => 'default',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '其他',
                'value'      => 'value2',
                'code'       => 'other',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '字典类型',
        'code'        => 'sys_dict_data_type',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '整型',
                'value'      => 1,
                'code'       => 'sys_dict_data_type',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '字符串',
                'value'      => 2,
                'code'       => 'sys_dict_data_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '是否',
        'code'        => 'yes_no',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '是',
                'value'      => 1,
                'code'       => 'yes_no',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '否',
                'value'      => 0,
                'code'       => 'yes_no',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '性别',
        'code'        => 'sex',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '男',
                'value'      => 1,
                'code'       => 'sex',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '女',
                'value'      => 2,
                'code'       => 'sex',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '菜单类型',
        'code'        => 'sys_menu_type',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '目录',
                'value'      => 1,
                'code'       => 'sys_menu_type',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '菜单',
                'value'      => 2,
                'code'       => 'sys_menu_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '按钮',
                'value'      => 3,
                'code'       => 'sys_menu_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '接口',
                'value'      => 4,
                'code'       => 'sys_menu_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '菜单打开类型',
        'code'        => 'sys_menu_open_type',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '无',
                'value'      => 0,
                'code'       => 'sys_menu_open_type',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '组件',
                'value'      => 1,
                'code'       => 'sys_menu_open_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '内链',
                'value'      => 2,
                'code'       => 'sys_menu_open_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '外链',
                'value'      => 3,
                'code'       => 'sys_menu_open_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '是否超级管理员',
        'code'        => 'sys_user_admin_type',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '超级管理员',
                'value'      => 1,
                'code'       => 'sys_user_admin_type',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '普通管理员',
                'value'      => 2,
                'code'       => 'sys_user_admin_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '角色类型',
        'code'        => 'sys_role_role_type',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '普通角色',
                'value'      => 1,
                'code'       => 'sys_role_role_type',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '数据角色',
                'value'      => 2,
                'code'       => 'sys_role_role_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '请求类型',
        'code'        => 'request_mode',
        'sort'        => 1,
        'data_type'   => 2,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => 'GET',
                'value'      => 'GET',
                'code'       => 'request_mode',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'POST',
                'value'      => 'POST',
                'code'       => 'request_mode',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'PUT',
                'value'      => 'PUT',
                'code'       => 'request_mode',
                'sort'       => 3,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'DELETE',
                'value'      => 'DELETE',
                'code'       => 'request_mode',
                'sort'       => 4,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '定时任务模式',
        'code'        => 'monitor_crontab_mode',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '单次',
                'value'      => 0,
                'code'       => 'monitor_crontab_mode',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '循环',
                'value'      => 1,
                'code'       => 'monitor_crontab_mode',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '定时任务类型',
        'code'        => 'monitor_crontab_type',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => 'url',
                'value'      => 1,
                'code'       => 'monitor_crontab_type',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'eval',
                'value'      => 2,
                'code'       => 'monitor_crontab_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'shell',
                'value'      => 3,
                'code'       => 'monitor_crontab_type',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '定时任务执行周期',
        'code'        => 'monitor_crontab_cycle',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '每天',
                'value'      => 1,
                'code'       => 'monitor_crontab_cycle',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '每小时',
                'value'      => 2,
                'code'       => 'monitor_crontab_cycle',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'N小时',
                'value'      => 3,
                'code'       => 'monitor_crontab_cycle',
                'sort'       => 3,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'N分钟',
                'value'      => 4,
                'code'       => 'monitor_crontab_cycle',
                'sort'       => 4,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'N秒',
                'value'      => 5,
                'code'       => 'monitor_crontab_cycle',
                'sort'       => 5,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '每星期',
                'value'      => 6,
                'code'       => 'monitor_crontab_cycle',
                'sort'       => 6,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '每年',
                'value'      => 7,
                'code'       => 'monitor_crontab_cycle',
                'sort'       => 7,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '每年',
                'value'      => 8,
                'code'       => 'monitor_crontab_cycle',
                'sort'       => 8,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => 'CPU监控',
        'code'        => 'monitor_server_cpu',
        'sort'        => 1,
        'data_type'   => 2,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '型号',
                'value'      => 'cpu_name',
                'code'       => 'monitor_server_cpu',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '物理核心数',
                'value'      => 'physical_cores',
                'code'       => 'monitor_server_cpu',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '逻辑核心数',
                'value'      => 'logical_cores',
                'code'       => 'monitor_server_cpu',
                'sort'       => 3,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '缓存大小(MB)',
                'value'      => 'cache_size_mb',
                'code'       => 'monitor_server_cpu',
                'sort'       => 4,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'CPU使用百分比',
                'value'      => 'cpu_usage_percentage',
                'code'       => 'monitor_server_cpu',
                'sort'       => 5,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '空闲 CPU 百分比',
                'value'      => 'free_cpu_percentage',
                'code'       => 'monitor_server_cpu',
                'sort'       => 6,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '内存监控',
        'code'        => 'monitor_server_memory',
        'sort'        => 1,
        'data_type'   => 2,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '内存使用率',
                'value'      => 'memory_usage_rate',
                'code'       => 'monitor_server_memory',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '总内存',
                'value'      => 'total_memory',
                'code'       => 'monitor_server_memory',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '可用内存',
                'value'      => 'available_memory',
                'code'       => 'monitor_server_memory',
                'sort'       => 3,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '已用内存',
                'value'      => 'used_memory',
                'code'       => 'monitor_server_memory',
                'sort'       => 4,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'PHP内存使用',
                'value'      => 'php_memory_usage',
                'code'       => 'monitor_server_memory',
                'sort'       => 5,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '配置分组',
        'code'        => 'sys_group',
        'sort'        => 1,
        'data_type'   => 2,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '系统配置',
                'value'      => 'system_config',
                'code'       => 'sys_group',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '上传配置',
                'value'      => 'system_storage',
                'code'       => 'sys_group',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],

];

