<?php
/**
 *+------------------
 * madong
 *+------------------
 * Copyright (c) https://gitee.com/motion-code  All rights reserved.
 *+------------------
 * Author: Mr. April (405784684@qq.com)
 *+------------------
 * Official Website: http://www.madong.tech
 */

return [
    [
        'title'     => '首页',
        'app'       => 'admin',
        'code'      => 'database',
        'icon'      => 'layui-icon-template-1',
        'sort'      => 1000,
        'type'      => 1,
        'is_show'   => 1,
        'is_link'   => 0,
        'is_cache'  => 1,
        'path'      => '/',
        'component' => 'BasicLayout',
        'redirect'  => "/analytics",
        'children'  => [
            [
                'title'     => '工作台',
                'app'       => 'admin',
                'code'      => 'Workspace',
                'icon'      => 'ant-design:home-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/workspace',
                'component' => '/dashboard/workspace/index',
                'redirect'  => "",
            ],
            [
                'title'     => '分析页',
                'app'       => 'admin',
                'code'      => 'Analytics',
                'icon'      => 'ant-design:home-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/analytics',
                'component' => '/dashboard/analytics/index',
                'redirect'  => "",
            ],
        ],
    ],
    [
        'title'     => '系统监控',
        'app'       => 'admin',
        'code'      => 'monitors',
        'icon'      => 'ant-design:video-camera-filled',
        'sort'      => 1000,
        'type'      => 1,
        'is_show'   => 1,
        'is_link'   => 0,
        'is_cache'  => 1,
        'path'      => '/monitors',
        'component' => 'BasicLayout',
        'redirect'  => "",
        'children'  => [
            [
                'title'     => 'Redis监控',
                'app'       => 'admin',
                'code'      => 'monitors:redis',
                'icon'      => 'ant-design:home-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/monitors/redis',
                'component' => '/monitor/redis/index',
                'redirect'  => "",
            ],
            [
                'title'     => '定时任务',
                'app'       => 'admin',
                'code'      => 'monitor:crontab',
                'icon'      => 'ant-design:home-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/monitors/crontab',
                'component' => '/monitor/crontab/index',
                'redirect'  => "",
            ],
            [
                'title'     => '性能监控',
                'app'       => 'admin',
                'code'      => 'monitors:monitor:server',
                'icon'      => 'ant-design:home-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/monitors/server',
                'component' => '/monitor/server/index',
                'redirect'  => "",
            ],
            [
                'title'     => '登录日志',
                'app'       => 'admin',
                'code'      => 'system:logs:login',
                'icon'      => 'ant-design:credit-card-filled',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/monitor/logs/login',
                'component' => '/system/logs/login/index',
                'redirect'  => "",
            ],
            [
                'title'     => '操作日志',
                'app'       => 'admin',
                'code'      => 'monitor:crontab',
                'icon'      => 'ant-design:schedule-filled',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/monitor/logs/operate',
                'component' => '/system/logs/operate/index',
                'redirect'  => "",
            ],
        ],
    ],

    [
        'title'     => '系统设置',
        'app'       => 'admin',
        'code'      => 'system',
        'icon'      => 'ant-design:video-camera-filled',
        'sort'      => 1000,
        'type'      => 1,
        'is_show'   => 1,
        'is_link'   => 0,
        'is_cache'  => 1,
        'path'      => '/system',
        'component' => 'BasicLayout',
        'redirect'  => "",
        'children'  => [
            [
                'title'     => '菜单管理',
                'app'       => 'admin',
                'code'      => 'system:menu',
                'icon'      => 'ant-design:home-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/system/menu',
                'component' => '/system/menu/index',
                'redirect'  => "",
                'children'  => [
                    [
                        'title'     => '添加',
                        'app'       => 'admin',
                        'code'      => 'system:menu:save',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:menu:remove',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:menu:update',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '详情',
                        'app'       => 'admin',
                        'code'      => 'system:menu:detail',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                ],
            ],
            [
                'title'     => '部门管理',
                'app'       => 'admin',
                'code'      => 'system:dept',
                'icon'      => 'ant-design:facebook-filled',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/system/dept',
                'component' => '/system/dept/index',
                'redirect'  => "",
                'children'  => [
                    [
                        'title'     => '添加',
                        'app'       => 'admin',
                        'code'      => 'system:dept:save',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:dept:remove',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:dept:update',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '详情',
                        'app'       => 'admin',
                        'code'      => 'system:dept:detail',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                ],
            ],
            [
                'title'     => '职位管理',
                'app'       => 'admin',
                'code'      => 'system:post',
                'icon'      => 'ant-design:facebook-filled',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/system/post',
                'component' => '/system/post/index',
                'redirect'  => "",
                'children'  => [
                    [
                        'title'     => '添加',
                        'app'       => 'admin',
                        'code'      => 'system:post:save',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:post:remove',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:post:update',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '详情',
                        'app'       => 'admin',
                        'code'      => 'system:post:detail',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                ],
            ],
            [
                'title'     => '角色管理',
                'app'       => 'admin',
                'code'      => 'system:role',
                'icon'      => 'ant-design:team-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/system/role',
                'component' => '/system/role/index',
                'redirect'  => "",
                'children'  => [
                    [
                        'title'     => '添加',
                        'app'       => 'admin',
                        'code'      => 'system:role:save',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:role:remove',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:role:update',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '详情',
                        'app'       => 'admin',
                        'code'      => 'system:role:detail',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '授权',
                        'app'       => 'admin',
                        'code'      => 'system:rbac:save_role_menu',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '用户',
                        'app'       => 'admin',
                        'code'      => 'system:rbac:user_list_by_role_id',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '移除用户',
                        'app'       => 'admin',
                        'code'      => 'system:rbac:remove_user_role',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                ],
            ],
            [
                'title'     => '数据字典',
                'app'       => 'admin',
                'code'      => 'system:dict',
                'icon'      => 'ant-design:profile-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/system/dict',
                'component' => '/system/dict/index',
                'redirect'  => "",
                'children'  => [
                    [
                        'title'     => '添加',
                        'app'       => 'admin',
                        'code'      => 'system:dict:save',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:dict:remove',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:dict:update',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '详情',
                        'app'       => 'admin',
                        'code'      => 'system:dict:detail',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '字典项列表',
                        'app'       => 'admin',
                        'code'      => 'system:dict-item:list',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '字典项添加',
                        'app'       => 'admin',
                        'code'      => 'system:dict_item:save',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '字典项删除',
                        'app'       => 'admin',
                        'code'      => 'system:dict_item:remove',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '字典项编辑',
                        'app'       => 'admin',
                        'code'      => 'system:dict_item:update',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '字典项详情',
                        'app'       => 'admin',
                        'code'      => 'system:dict_item:detail',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                ],
            ],
            [
                'title'     => '用户管理',
                'app'       => 'admin',
                'code'      => 'system:user',
                'icon'      => 'ant-design:user-add-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/system/user',
                'component' => '/system/user/index',
                'redirect'  => "",
                'children'  => [
                    [
                        'title'     => '添加',
                        'app'       => 'admin',
                        'code'      => 'system:user:save',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:user:remove',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:user:update',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '详情',
                        'app'       => 'admin',
                        'code'      => 'system:user:detail',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '重置密码',
                        'app'       => 'admin',
                        'code'      => 'system:user:reset_password',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '授权角色',
                        'app'       => 'admin',
                        'code'      => 'system:user:grant_role',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '冻结用户',
                        'app'       => 'admin',
                        'code'      => 'system:user:locked',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                    [
                        'title'     => '取消冻结',
                        'app'       => 'admin',
                        'code'      => 'system:user:un_locked',
                        'icon'      => '',
                        'sort'      => 1000,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 1,
                        'path'      => '',
                        'component' => '',
                        'redirect'  => "",
                    ],
                ],
            ],
            [
                'title'     => '附件管理',
                'app'       => 'admin',
                'code'      => 'system:files',
                'icon'      => 'ant-design:folder-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/system/files',
                'component' => '/system/files/index',
                'redirect'  => "",
            ],
            [
                'title'     => '系统参数',
                'app'       => 'admin',
                'code'      => 'system:config',
                'icon'      => 'ant-design:tool-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 1,
                'path'      => '/system/config',
                'component' => '/system/config/index',
                'redirect'  => "",
            ],
        ],
    ],

];
