<?php
/**
 *+------------------
 * madong
 *+------------------
 * Copyright (c) https://gitcode.com/motion-code  All rights reserved.
 *+------------------
 * Author: Mr. April (405784684@qq.com)
 *+------------------
 * Official Website: https://madong.tech
 */


namespace packages\jwt\tests;


use madong\jwt\JwtToken;

class JwtTokenTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function generateToken()
    {
        $user = [
            'id'  => 1,
            'name'  => 'test',
            'email' => 'test@163.com'
        ];
        $token = JwtToken::generateToken($user);
        self::assertIsArray($token);
    }
}