<?php
/**
 *+------------------
 * madong
 *+------------------
 * Copyright (c) https://gitee.com/motion-code  All rights reserved.
 *+------------------
 * Author: Mr. April (405784684@qq.com)
 *+------------------
 * Official Website: http://www.madong.tech
 */

/**
 * 系统配置数据
 */
return [
    [
        "group_code" => "local",
        "code"       => "root",
        "name"       => "",
        "content"    => "public",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732029810",
        "created_by" => "",
        "updated_at" => "1732029878",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "local",
        "code"       => "dirname",
        "name"       => "",
        "content"    => "upload",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732029810",
        "created_by" => "",
        "updated_at" => "1732029878",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "local",
        "code"       => "domain",
        "name"       => "",
        "content"    => "http=>>//43.138.153.216=>>8899/",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732029810",
        "created_by" => "",
        "updated_at" => "1732029878",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "oss",
        "code"       => "accessKeyId",
        "name"       => "",
        "content"    => "1",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030257",
        "created_by" => "",
        "updated_at" => "1732030257",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "oss",
        "code"       => "accessKeySecret",
        "name"       => "",
        "content"    => "2",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030257",
        "created_by" => "",
        "updated_at" => "1732030257",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "oss",
        "code"       => "bucket",
        "name"       => "",
        "content"    => "3",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030257",
        "created_by" => "",
        "updated_at" => "1732030257",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "oss",
        "code"       => "dirname",
        "name"       => "",
        "content"    => "4",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030257",
        "created_by" => "",
        "updated_at" => "1732030257",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "oss",
        "code"       => "domain",
        "name"       => "",
        "content"    => "5",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030257",
        "created_by" => "",
        "updated_at" => "1732030257",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "oss",
        "code"       => "endpoint",
        "name"       => "",
        "content"    => "6",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030257",
        "created_by" => "",
        "updated_at" => "1732030257",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "oss",
        "code"       => "remark",
        "name"       => "",
        "content"    => "7",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030257",
        "created_by" => "",
        "updated_at" => "1732030257",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "cos",
        "code"       => "secretId",
        "name"       => "",
        "content"    => "11",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030301",
        "created_by" => "",
        "updated_at" => "1732030301",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "cos",
        "code"       => "secretKey",
        "name"       => "",
        "content"    => "22",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030301",
        "created_by" => "",
        "updated_at" => "1732030301",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "cos",
        "code"       => "bucket",
        "name"       => "",
        "content"    => "33",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030301",
        "created_by" => "",
        "updated_at" => "1732030301",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "cos",
        "code"       => "dirname",
        "name"       => "",
        "content"    => "44",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030301",
        "created_by" => "",
        "updated_at" => "1732030301",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "cos",
        "code"       => "domain",
        "name"       => "",
        "content"    => "55",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030301",
        "created_by" => "",
        "updated_at" => "1732030301",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "cos",
        "code"       => "region",
        "name"       => "",
        "content"    => "66",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030301",
        "created_by" => "",
        "updated_at" => "1732030301",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "cos",
        "code"       => "remark",
        "name"       => "",
        "content"    => "77",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030301",
        "created_by" => "",
        "updated_at" => "1732030301",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "qiniu",
        "code"       => "accessKey",
        "name"       => "",
        "content"    => "99",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030319",
        "created_by" => "",
        "updated_at" => "1732030319",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "qiniu",
        "code"       => "secretKey",
        "name"       => "",
        "content"    => "88",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030319",
        "created_by" => "",
        "updated_at" => "1732030319",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "qiniu",
        "code"       => "bucket",
        "name"       => "",
        "content"    => "7",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030319",
        "created_by" => "",
        "updated_at" => "1732030319",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "qiniu",
        "code"       => "dirname",
        "name"       => "",
        "content"    => "78",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030319",
        "created_by" => "",
        "updated_at" => "1732030319",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "qiniu",
        "code"       => "domain",
        "name"       => "",
        "content"    => "8",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030319",
        "created_by" => "",
        "updated_at" => "1732030319",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "qiniu",
        "code"       => "region",
        "name"       => "",
        "content"    => "",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030319",
        "created_by" => "",
        "updated_at" => "1732030319",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "qiniu",
        "code"       => "remark",
        "name"       => "",
        "content"    => "897",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030319",
        "created_by" => "",
        "updated_at" => "1732030319",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "key",
        "name"       => "",
        "content"    => "12",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "secret",
        "name"       => "",
        "content"    => "12",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "bucket",
        "name"       => "",
        "content"    => "12",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "dirname",
        "name"       => "",
        "content"    => "12",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "domain",
        "name"       => "",
        "content"    => "12",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "endpoint",
        "name"       => "",
        "content"    => "12",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "region",
        "name"       => "",
        "content"    => "12",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "acl",
        "name"       => "",
        "content"    => "6",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "s3",
        "code"       => "remark",
        "name"       => "",
        "content"    => "4",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732030332",
        "created_by" => "",
        "updated_at" => "1732030332",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "email_setting",
        "code"       => "SMTPSecure",
        "name"       => "",
        "content"    => "ssl",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732031603",
        "created_by" => "",
        "updated_at" => "1732429949",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "email_setting",
        "code"       => "Host",
        "name"       => "",
        "content"    => "smtp.qq.com",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732031603",
        "created_by" => "",
        "updated_at" => "1732429949",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "email_setting",
        "code"       => "Port",
        "name"       => "",
        "content"    => "465",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732031603",
        "created_by" => "",
        "updated_at" => "1732429949",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "email_setting",
        "code"       => "Username",
        "name"       => "",
        "content"    => "kzhzjdyw888@qq.com",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732031603",
        "created_by" => "",
        "updated_at" => "1732429949",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "email_setting",
        "code"       => "Password",
        "name"       => "",
        "content"    => "",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732031603",
        "created_by" => "",
        "updated_at" => "1732429949",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "email_setting",
        "code"       => "From",
        "name"       => "",
        "content"    => "",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732031603",
        "created_by" => "",
        "updated_at" => "1732429949",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "email_setting",
        "code"       => "FromName",
        "name"       => "",
        "content"    => "kzhzjdyw888@qq.com",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732031603",
        "created_by" => "",
        "updated_at" => "1732429949",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "basic_upload_setting",
        "code"       => "mode",
        "name"       => "上传模式",
        "content"    => "local",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732415050",
        "created_by" => "",
        "updated_at" => "1732429734",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "basic_upload_setting",
        "code"       => "single_limit",
        "name"       => "上传大小",
        "content"    => "1024",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732415050",
        "created_by" => "",
        "updated_at" => "1732429734",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "basic_upload_setting",
        "code"       => "total_limit",
        "name"       => "文件限制",
        "content"    => "1024",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732415050",
        "created_by" => "",
        "updated_at" => "1732429734",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "basic_upload_setting",
        "code"       => "nums",
        "name"       => "数量限制",
        "content"    => "10",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732415050",
        "created_by" => "",
        "updated_at" => "1732429734",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "basic_upload_setting",
        "code"       => "exclude",
        "name"       => "不允许文件类型",
        "content"    => "php,ext,exe",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732415050",
        "created_by" => "",
        "updated_at" => "1732429734",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_open",
        "name"       => "站点开启",
        "content"    => "1",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_url",
        "name"       => "网站地址",
        "content"    => "http=>>//43.138.153.216=>>8899/",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_name",
        "name"       => "站点名称",
        "content"    => "MaDong Admin",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_logo",
        "name"       => "站点Logo",
        "content"    => "https=>>//madong.tech/assets/images/logo.svg",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_network_security",
        "name"       => "网备案号",
        "content"    => "2024042441号-2",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_description",
        "name"       => "网站描述",
        "content"    => "快速开发框架",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_record_no",
        "name"       => "网站ICP",
        "content"    => "2024042442",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_icp_url",
        "name"       => "ICP URL",
        "content"    => "https=>>//beian.miit.gov.cn/",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "site_setting",
        "code"       => "site_network_security_url",
        "name"       => "网安备案链接",
        "content"    => "",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429827",
        "created_by" => "",
        "updated_at" => "1732430264",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "sms_setting",
        "code"       => "enable",
        "name"       => "是否开启",
        "content"    => "1",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429997",
        "created_by" => "",
        "updated_at" => "1732430097",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "sms_setting",
        "code"       => "access_key_id",
        "name"       => "access_key_id",
        "content"    => "234813346262818816",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429997",
        "created_by" => "",
        "updated_at" => "1732430097",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "sms_setting",
        "code"       => "access_key_secret",
        "name"       => "access_key_secret",
        "content"    => "238164553517768704",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429997",
        "created_by" => "",
        "updated_at" => "1732430097",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
    [
        "group_code" => "sms_setting",
        "code"       => "sign_name",
        "name"       => "sign_name",
        "content"    => "【码动开源】，你的验证码是{code}，有效期5分钟。",
        "is_sys"     => "0",
        "enabled"    => "1",
        "created_at" => "1732429997",
        "created_by" => "",
        "updated_at" => "1732430097",
        "updated_by" => "",
        "deleted_at" => "",
        "remark"     => "",
    ],
];
