<?php
/**
 *+------------------
 * madong
 *+------------------
 * Copyright (c) https://gitee.com/motion-code  All rights reserved.
 *+------------------
 * Author: Mr. April (405784684@qq.com)
 *+------------------
 * Official Website: http://www.madong.tech
 */

return [
    [
        'group_code'  => 'default',
        'name'        => '所属分组',
        'code'        => 'sys_dict_group_code',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '默认分组',
                'value'      => 'value1',
                'code'       => 'default',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '其他',
                'value'      => 'value2',
                'code'       => 'other',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => 'CPU监控',
        'code'        => 'monitor_server_cpu',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '型号',
                'value'      => 'cpu_name',
                'code'       => 'monitor_server_cpu',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '物理核心数',
                'value'      => 'physical_cores',
                'code'       => 'monitor_server_cpu',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '逻辑核心数',
                'value'      => 'logical_cores',
                'code'       => 'monitor_server_cpu',
                'sort'       => 3,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '缓存大小(MB)',
                'value'      => 'cache_size_mb',
                'code'       => 'monitor_server_cpu',
                'sort'       => 4,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'CPU使用百分比',
                'value'      => 'cpu_usage_percentage',
                'code'       => 'monitor_server_cpu',
                'sort'       => 5,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '空闲 CPU 百分比',
                'value'      => 'free_cpu_percentage',
                'code'       => 'monitor_server_cpu',
                'sort'       => 6,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ],
    [
        'group_code'  => 'default',
        'name'        => '内存监控',
        'code'        => 'monitor_server_memory',
        'sort'        => 1,
        'data_type'   => 1,
        'description' => '',
        'enabled'     => 1,
        'created_by'  => 1,
        'updated_by'  => 1,
        'items'       => [
            [
                'label'      => '内存使用率',
                'value'      => 'memory_usage_rate',
                'code'       => 'monitor_server_memory',
                'sort'       => 1,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '总内存',
                'value'      => 'total_memory',
                'code'       => 'monitor_server_memory',
                'sort'       => 2,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '可用内存',
                'value'      => 'available_memory',
                'code'       => 'monitor_server_memory',
                'sort'       => 3,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => '已用内存',
                'value'      => 'used_memory',
                'code'       => 'monitor_server_memory',
                'sort'       => 4,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
            [
                'label'      => 'PHP内存使用',
                'value'      => 'php_memory_usage',
                'code'       => 'monitor_server_memory',
                'sort'       => 5,
                'enabled'    => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'remark'     => '',
            ],
        ],
    ]
];

