<?php
/**
 *+------------------
 * madong
 *+------------------
 * Copyright (c) https://gitee.com/motion-code  All rights reserved.
 *+------------------
 * Author: Mr. April (405784684@qq.com)
 *+------------------
 * Official Website: http://www.madong.tech
 */

return  [
    [
        'title'     => '首页',
        'app'       => 'admin',
        'code'      => 'Dashboard',
        'icon'      => 'ant-design:home-outlined',
        'sort'      => -1,
        'type'      => 1,
        'is_show'   => 1,
        'is_link'   => 0,
        'is_cache'  => 0,
        'path'      => '/',
        'component' => 'BasicLayout',
        'redirect'  => '/workspace',
        'children'  => [
            [
                'title'     => '分析页',
                'app'       => 'admin',
                'code'      => 'Analytics',
                'icon'      => 'ant-design:home-outlined',
                'sort'      => -1,
                'type'      => 1,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/analytics',
                'component' => '/dashboard/analytics/index',
                'redirect'  => null,
            ],
            [
                'title'     => '工作台',
                'app'       => 'admin',
                'code'      => 'Workspace',
                'icon'      => 'ant-design:home-outlined',
                'sort'      => -1,
                'type'      => 1,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/workspace',
                'component' => '/dashboard/workspace/index',
                'redirect'  => null,
            ],
        ],
    ],
    [
        'title'     => '系统监控',
        'app'       => 'admin',
        'code'      => 'monitors',
        'icon'      => 'ant-design:video-camera-filled',
        'sort'      => 999,
        'type'      => 1,
        'is_show'   => 1,
        'is_link'   => 0,
        'is_cache'  => 0,
        'path'      => '/monitors',
        'component' => 'BasicLayout',
        'redirect'  => null,
        'children'  => [
            [
                'title'     => 'Redis监控',
                'app'       => 'admin',
                'code'      => 'monitors:redis',
                'icon'      => 'ant-design:trademark-outlined',
                'sort'      => 999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/monitors/redis',
                'component' => '/monitor/redis/index',
                'redirect'  => null,
            ],
            [
                'title'     => '定时任务',
                'app'       => null,
                'code'      => 'monitor:crontab',
                'icon'      => 'ant-design:dashboard-filled',
                'sort'      => 999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/monitor/crontab',
                'component' => '/monitor/crontab/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '新增',
                        'app'       => null,
                        'code'      => 'monitor:crontab:create',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => null,
                        'code'      => 'monitor:crontab:edit',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '执行',
                        'app'       => null,
                        'code'      => 'monitor:crontab:execute',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => null,
                        'code'      => 'monitor:crontab:delete',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '日志',
                        'app'       => null,
                        'code'      => 'monitor:crontab:logs',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '停止',
                        'app'       => null,
                        'code'      => 'monitor:crontab:pause',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '启动',
                        'app'       => null,
                        'code'      => 'monitor:crontab:resume',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '性能监控',
                'app'       => 'admin',
                'code'      => 'monitors:monitor:server',
                'icon'      => 'ant-design:line-chart-outlined',
                'sort'      => 999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/monitors/server',
                'component' => '/monitor/server/index',
                'redirect'  => null,
            ],
            [
                'title'     => '操作日志',
                'app'       => 'admin',
                'code'      => 'system:logs_operate',
                'icon'      => 'ant-design:schedule-filled',
                'sort'      => 999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/monitor/logs/operate',
                'component' => '/system/logs/operate/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '删除',
                        'app'       => null,
                        'code'      => 'system:logs_operate:delete',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '详情',
                        'app'       => null,
                        'code'      => 'system:logs_operate:detail',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '登录日志',
                'app'       => 'admin',
                'code'      => 'system:logs:login',
                'icon'      => 'ant-design:credit-card-filled',
                'sort'      => 999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/monitor/logs/login',
                'component' => '/system/logs/login/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '删除',
                        'app'       => null,
                        'code'      => 'system:logs_login:delete',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
        ],
    ],
    [
        'title'     => '系统设置',
        'app'       => 'admin',
        'code'      => 'system',
        'icon'      => 'ant-design:setting-outlined',
        'sort'      => 1000,
        'type'      => 1,
        'is_show'   => 1,
        'is_link'   => 0,
        'is_cache'  => 1,
        'path'      => '/system',
        'component' => 'BasicLayout',
        'redirect'  => '',
        'children'  => [
            [
                'title'     => '附件管理',
                'app'       => null,
                'code'      => 'system:files',
                'icon'      => 'ant-design:folder-outlined',
                'sort'      => 999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/files',
                'component' => '/system/files/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '删除',
                        'app'       => null,
                        'code'      => 'system:files:delete',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '下载',
                        'app'       => null,
                        'code'      => 'system:files:download',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '通知公告',
                'app'       => null,
                'code'      => 'system:notice',
                'icon'      => 'ant-design:comment-outlined',
                'sort'      => 999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/notice',
                'component' => '/system/notice/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '编辑',
                        'app'       => null,
                        'code'      => 'system:notice:edit',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => null,
                        'code'      => 'system:notice:delete',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '新增',
                        'app'       => null,
                        'code'      => 'system:notice:create',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '菜单管理',
                'app'       => 'admin',
                'code'      => 'system:menu',
                'icon'      => 'ant-design:menu-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/menu',
                'component' => '/system/menu/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '新增',
                        'app'       => 'admin',
                        'code'      => 'system:menu:create',
                        'icon'      => null,
                        'sort'      => 10,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:menu:delete',
                        'icon'      => null,
                        'sort'      => 20,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:menu:edit',
                        'icon'      => null,
                        'sort'      => 30,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '部门管理',
                'app'       => 'admin',
                'code'      => 'system:dept',
                'icon'      => 'ant-design:facebook-filled',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/dept',
                'component' => '/system/dept/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '新增',
                        'app'       => 'admin',
                        'code'      => 'system:dept:create',
                        'icon'      => null,
                        'sort'      => 10,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:dept:delete',
                        'icon'      => null,
                        'sort'      => 20,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:dept:edit',
                        'icon'      => null,
                        'sort'      => 30,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '职位管理',
                'app'       => 'admin',
                'code'      => 'system:post',
                'icon'      => 'ant-design:database-filled',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/post',
                'component' => '/system/post/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '添加',
                        'app'       => 'admin',
                        'code'      => 'system:post:create',
                        'icon'      => null,
                        'sort'      => 10,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:post:delete',
                        'icon'      => null,
                        'sort'      => 20,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:post:edit',
                        'icon'      => null,
                        'sort'      => 30,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '用户管理',
                'app'       => 'admin',
                'code'      => 'system:user',
                'icon'      => 'ant-design:user-add-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/user',
                'component' => '/system/user/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '添加',
                        'app'       => 'admin',
                        'code'      => 'system:user:create',
                        'icon'      => null,
                        'sort'      => 10,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:user:delete',
                        'icon'      => null,
                        'sort'      => 20,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:user:edit',
                        'icon'      => null,
                        'sort'      => 30,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '重置密码',
                        'app'       => 'admin',
                        'code'      => 'system:user:reset_password',
                        'icon'      => null,
                        'sort'      => 50,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '冻结用户',
                        'app'       => 'admin',
                        'code'      => 'system:user:locked',
                        'icon'      => null,
                        'sort'      => 70,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '取消冻结',
                        'app'       => 'admin',
                        'code'      => 'system:user:un_locked',
                        'icon'      => null,
                        'sort'      => 80,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '角色管理',
                'app'       => 'admin',
                'code'      => 'system:role',
                'icon'      => 'ant-design:team-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/role',
                'component' => '/system/role/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '新增',
                        'app'       => 'admin',
                        'code'      => 'system:role:create',
                        'icon'      => null,
                        'sort'      => 10,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:role:delete',
                        'icon'      => null,
                        'sort'      => 20,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:rbac:edit',
                        'icon'      => null,
                        'sort'      => 50,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '分配用户',
                        'app'       => 'admin',
                        'code'      => 'system:role:user',
                        'icon'      => null,
                        'sort'      => 60,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '添加用户',
                        'app'       => null,
                        'code'      => 'system:auth:user_role',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '移除用户',
                        'app'       => null,
                        'code'      => 'system:auth:remove_user_role',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '数据字典',
                'app'       => 'admin',
                'code'      => 'system:dict',
                'icon'      => 'ant-design:profile-outlined',
                'sort'      => 1000,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/dict',
                'component' => '/system/dict/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '新增',
                        'app'       => 'admin',
                        'code'      => 'system:dict:create',
                        'icon'      => null,
                        'sort'      => 10,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => 'admin',
                        'code'      => 'system:dict:delete',
                        'icon'      => null,
                        'sort'      => 20,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '编辑',
                        'app'       => 'admin',
                        'code'      => 'system:dict:edit',
                        'icon'      => null,
                        'sort'      => 30,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '枚举字典',
                        'app'       => null,
                        'code'      => 'system:dict:enum',
                        'icon'      => null,
                        'sort'      => 40,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '字典项列表',
                        'app'       => 'admin',
                        'code'      => 'system:dict_item:list',
                        'icon'      => null,
                        'sort'      => 50,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '字典项添加',
                        'app'       => 'admin',
                        'code'      => 'system:dict_item:create',
                        'icon'      => null,
                        'sort'      => 60,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '字典项删除',
                        'app'       => 'admin',
                        'code'      => 'system:dict_item:delete',
                        'icon'      => null,
                        'sort'      => 70,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '字典项编辑',
                        'app'       => 'admin',
                        'code'      => 'system:dict_item:edit',
                        'icon'      => null,
                        'sort'      => 80,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
            [
                'title'     => '系统参数',
                'app'       => null,
                'code'      => 'system:config',
                'icon'      => 'ant-design:tool-outlined',
                'sort'      => 999999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/systen/config',
                'component' => '/system/config/index',
                'redirect'  => null,
            ],
            [
                'title'     => '数据回收',
                'app'       => null,
                'code'      => 'system:recycle_bin',
                'icon'      => 'ant-design:rest-filled',
                'sort'      => 999999999,
                'type'      => 2,
                'is_show'   => 1,
                'is_link'   => 0,
                'is_cache'  => 0,
                'path'      => '/system/recycle-bin',
                'component' => '/system/recycle-bin/index',
                'redirect'  => null,
                'children'  => [
                    [
                        'title'     => '详情',
                        'app'       => null,
                        'code'      => 'system:recycle_bin:detail',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '恢复',
                        'app'       => null,
                        'code'      => 'system:recycle_bin:recover',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                    [
                        'title'     => '删除',
                        'app'       => null,
                        'code'      => 'system:recycle_bin:remove',
                        'icon'      => null,
                        'sort'      => 999,
                        'type'      => 3,
                        'is_show'   => 1,
                        'is_link'   => 0,
                        'is_cache'  => 0,
                        'path'      => null,
                        'component' => null,
                        'redirect'  => null,
                    ],
                ],
            ],
        ],
    ],
];
