<?php
/**
 *+------------------
 * madong
 *+------------------
 * Copyright (c) https://gitcode.com/motion-code  All rights reserved.
 *+------------------
 * Author: Mr. April (405784684@qq.com)
 *+------------------
 * Official Website: https://madong.tech
 */

return [
    [
        "app"       => "admin",
        "title"     => "首页",
        "code"      => "Dashboard",
        "level"     => null,
        "type"      => 1,
        "sort"      => -1,
        "path"      => "/",
        "component" => "BasicLayout",
        "redirect"  => "/workspace",
        "icon"      => "ant-design:home-outlined",
        "is_show"   => 1,
        "is_link"   => 0,
        "link_url"  => null,
        "enabled"   => 1,
        "open_type" => 0,
        "is_cache"  => 0,
        "is_sync"   => 1,
        "is_affix"  => 0,
        "methods"   => "GET",
        "is_frame"  => null,
        "children"  => [
            [
                "app"       => "admin",
                "title"     => "分析页",
                "code"      => "Analytics",
                "level"     => null,
                "type"      => 1,
                "sort"      => -1,
                "path"      => "/analytics",
                "component" => "/dashboard/analytics/index",
                "redirect"  => null,
                "icon"      => "ant-design:home-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,

            ],
            [

                "app"       => "admin",
                "title"     => "工作台",
                "code"      => "Workspace",
                "level"     => null,
                "type"      => 1,
                "sort"      => -1,
                "path"      => "/workspace",
                "component" => "/dashboard/workspace/index",
                "redirect"  => null,
                "icon"      => "ant-design:home-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 1,
                "methods"   => "GET",
                "is_frame"  => null,

            ],
        ],
    ],
    [

        "app"       => "admin",
        "title"     => "系统监控",
        "code"      => "monitors",
        "level"     => null,
        "type"      => 1,
        "sort"      => 999,
        "path"      => "/monitors",
        "component" => "BasicLayout",
        "redirect"  => null,
        "icon"      => "ant-design:video-camera-filled",
        "is_show"   => 1,
        "is_link"   => 0,
        "link_url"  => null,
        "enabled"   => 1,
        "open_type" => 0,
        "is_cache"  => 0,
        "is_sync"   => 1,
        "is_affix"  => 0,

        "methods"  => "GET",
        "is_frame" => null,

        "children" => [
            [

                "app"       => "admin",
                "title"     => "Redis监控",
                "code"      => "monitors:redis",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999,
                "path"      => "/monitors/redis",
                "component" => "/monitor/redis/index",
                "redirect"  => null,
                "icon"      => "ant-design:trademark-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,

                "methods"  => "GET",
                "is_frame" => null,

            ],
            [

                "app"       => "admin",
                "title"     => "性能监控",
                "code"      => "monitors:monitor:server",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999,
                "path"      => "/monitors/server",
                "component" => "/monitor/server/index",
                "redirect"  => null,
                "icon"      => "ant-design:line-chart-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,

                "methods"  => "GET",
                "is_frame" => null,

            ],
            [

                "app"       => "admin",
                "title"     => "操作日志",
                "code"      => "system:logs_operate",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999,
                "path"      => "/monitor/logs/operate",
                "component" => "/system/logs/operate/index",
                "redirect"  => null,
                "icon"      => "ant-design:schedule-filled",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [

                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:logs_operate:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,

                    ],
                    [

                        "app"       => "admin",
                        "title"     => "详情",
                        "code"      => "system:logs_operate:detail",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
            [

                "app"       => "admin",
                "title"     => "登录日志",
                "code"      => "system:logs:login",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999,
                "path"      => "/monitor/logs/login",
                "component" => "/system/logs/login/index",
                "redirect"  => null,
                "icon"      => "ant-design:credit-card-filled",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:logs_login:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
        ],
    ],
    [
        "app"       => "admin",
        "title"     => "开发平台",
        "code"      => "dev",
        "level"     => null,
        "type"      => 1,
        "sort"      => 999,
        "path"      => "/dev",
        "component" => null,
        "redirect"  => null,
        "icon"      => "ant-design:appstore-add-outlined",
        "is_show"   => 1,
        "is_link"   => 0,
        "link_url"  => null,
        "enabled"   => 1,
        "open_type" => 1,
        "is_cache"  => 0,
        "is_sync"   => 1,
        "is_affix"  => 0,
        "methods"   => "GET",
        "is_frame"  => null,
        "children"  => [
//            [
//                "app"       => "admin",
//                "title"     => "代码生成",
//                "code"      => "dev:generate",
//                "level"     => null,
//                "type"      => 2,
//                "sort"      => 999,
//                "path"      => "/dev/generate",
//                "component" => "/dev/generate/index",
//                "redirect"  => null,
//                "icon"      => "streamline:ai-generate-variation-spark-solid",
//                "is_show"   => 1,
//                "is_link"   => 0,
//                "link_url"  => null,
//                "enabled"   => 0,
//                "open_type" => 1,
//                "is_cache"  => 0,
//                "is_sync"   => 1,
//                "is_affix"  => 0,
//                "methods"   => "GET",
//                "is_frame"  => null,
//            ],
[
    "app"       => "admin",
    "title"     => "定时任务",
    "code"      => "dev:crontab",
    "level"     => null,
    "type"      => 2,
    "sort"      => 999,
    "path"      => "/dev/crontab",
    "component" => "/dev/crontab/index",
    "redirect"  => null,
    "icon"      => "arcticons:jobstreet",
    "is_show"   => 1,
    "is_link"   => 0,
    "link_url"  => null,
    "enabled"   => 1,
    "open_type" => 1,
    "is_cache"  => 0,
    "is_sync"   => 1,
    "is_affix"  => 0,
    "methods"   => "GET",
    "is_frame"  => null,
    "children"  => [
        [
            "app"       => "admin",
            "title"     => "删除",
            "code"      => "dev:crontab:delete",
            "level"     => null,
            "type"      => 3,
            "sort"      => 999,
            "path"      => null,
            "component" => null,
            "redirect"  => null,
            "icon"      => null,
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
        ],
        [
            "app"       => "admin",
            "title"     => "执行",
            "code"      => "dev:crontab:execute",
            "level"     => null,
            "type"      => 3,
            "sort"      => 999,
            "path"      => null,
            "component" => null,
            "redirect"  => null,
            "icon"      => null,
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
        ],
        [
            "app"       => "admin",
            "title"     => "编辑",
            "code"      => "dev:crontab:edit",
            "level"     => null,
            "type"      => 3,
            "sort"      => 999,
            "path"      => null,
            "component" => null,
            "redirect"  => null,
            "icon"      => null,
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
        ],
        [
            "app"       => "admin",
            "title"     => "新增",
            "code"      => "dev:crontab:create",
            "level"     => null,
            "type"      => 3,
            "sort"      => 999,
            "path"      => null,
            "component" => null,
            "redirect"  => null,
            "icon"      => null,
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
        ],
        [
            "app"       => "admin",
            "title"     => "停止",
            "code"      => "dev:crontab:pause",
            "level"     => null,
            "type"      => 3,
            "sort"      => 999,
            "path"      => null,
            "component" => null,
            "redirect"  => null,
            "icon"      => null,
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
        ],
        [
            "app"       => "admin",
            "title"     => "日志",
            "code"      => "dev:crontab:logs",
            "level"     => null,
            "type"      => 3,
            "sort"      => 999,
            "path"      => null,
            "component" => null,
            "redirect"  => null,
            "icon"      => null,
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
        ],
        [
            "app"       => "admin",
            "title"     => "恢复",
            "code"      => "dev:crontab:resume",
            "level"     => null,
            "type"      => 3,
            "sort"      => 999,
            "path"      => null,
            "component" => null,
            "redirect"  => null,
            "icon"      => null,
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
        ],
    ],
],
[
    "app"       => "admin",
    "title"     => "网关管理",
    "code"      => "dev:gateway",
    "level"     => null,
    "type"      => 1,
    "sort"      => 999,
    "path"      => "/dev/gateway",
    "component" => null,
    "redirect"  => null,
    "icon"      => "ant-design:gateway-outlined",
    "is_show"   => 1,
    "is_link"   => 0,
    "link_url"  => null,
    "enabled"   => 1,
    "open_type" => 1,
    "is_cache"  => 0,
    "is_sync"   => 1,
    "is_affix"  => 0,
    "methods"   => "GET",
    "is_frame"  => null,
    "children"  => [
        [
            "app"       => "admin",
            "title"     => "限流规则",
            "code"      => "dev:gateway:limit",
            "level"     => null,
            "type"      => 2,
            "sort"      => 999,
            "path"      => "/dev/gateway/limiter",
            "component" => "/dev/gateway/limiter/index",
            "redirect"  => null,
            "icon"      => "carbon-rule",
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
            "children"  => [
                [
                    "app"       => "admin",
                    "title"     => "删除",
                    "code"      => "dev:gateway_limiter:delete",
                    "level"     => null,
                    "type"      => 3,
                    "sort"      => 999,
                    "path"      => null,
                    "component" => null,
                    "redirect"  => null,
                    "icon"      => null,
                    "is_show"   => 1,
                    "is_link"   => 0,
                    "link_url"  => null,
                    "enabled"   => 1,
                    "open_type" => 1,
                    "is_cache"  => 0,
                    "is_sync"   => 1,
                    "is_affix"  => 0,
                    "methods"   => "GET",
                    "is_frame"  => null,
                ],
                [
                    "app"       => "admin",
                    "title"     => "编辑",
                    "code"      => "dev:gateway_limiter:edit",
                    "level"     => null,
                    "type"      => 3,
                    "sort"      => 999,
                    "path"      => null,
                    "component" => null,
                    "redirect"  => null,
                    "icon"      => null,
                    "is_show"   => 1,
                    "is_link"   => 0,
                    "link_url"  => null,
                    "enabled"   => 1,
                    "open_type" => 1,
                    "is_cache"  => 0,
                    "is_sync"   => 1,
                    "is_affix"  => 0,
                    "methods"   => "GET",
                    "is_frame"  => null,
                ],
                [
                    "app"       => "admin",
                    "title"     => "新增",
                    "code"      => "dev:gateway_limiter:create",
                    "level"     => null,
                    "type"      => 3,
                    "sort"      => 999,
                    "path"      => null,
                    "component" => null,
                    "redirect"  => null,
                    "icon"      => null,
                    "is_show"   => 1,
                    "is_link"   => 0,
                    "link_url"  => null,
                    "enabled"   => 1,
                    "open_type" => 1,
                    "is_cache"  => 0,
                    "is_sync"   => 1,
                    "is_affix"  => 0,
                    "methods"   => "GET",
                    "is_frame"  => null,
                ],
                [
                    "app"       => "admin",
                    "title"     => "状态",
                    "code"      => "dev:gateway_limiter:status",
                    "level"     => null,
                    "type"      => 3,
                    "sort"      => 999,
                    "path"      => null,
                    "component" => null,
                    "redirect"  => null,
                    "icon"      => null,
                    "is_show"   => 1,
                    "is_link"   => 0,
                    "link_url"  => null,
                    "enabled"   => 1,
                    "open_type" => 1,
                    "is_cache"  => 0,
                    "is_sync"   => 1,
                    "is_affix"  => 0,
                    "methods"   => "GET",
                    "is_frame"  => null,
                ],
            ],
        ],
        [
            "app"       => "admin",
            "title"     => "限访名单",
            "code"      => "dev:gateway:blacklist",
            "level"     => null,
            "type"      => 2,
            "sort"      => 999,
            "path"      => "/dev/gateway/blacklist",
            "component" => "/dev/gateway/blacklist/index",
            "redirect"  => null,
            "icon"      => "carbon-ai-status-rejected",
            "is_show"   => 1,
            "is_link"   => 0,
            "link_url"  => null,
            "enabled"   => 1,
            "open_type" => 1,
            "is_cache"  => 0,
            "is_sync"   => 1,
            "is_affix"  => 0,
            "methods"   => "GET",
            "is_frame"  => null,
            "children"  => [
                [
                    "app"       => "admin",
                    "title"     => "新增",
                    "code"      => "dev:gateway_blacklist:create",
                    "level"     => null,
                    "type"      => 3,
                    "sort"      => 999,
                    "path"      => null,
                    "component" => null,
                    "redirect"  => null,
                    "icon"      => null,
                    "is_show"   => 1,
                    "is_link"   => 0,
                    "link_url"  => null,
                    "enabled"   => 1,
                    "open_type" => 1,
                    "is_cache"  => 0,
                    "is_sync"   => 1,
                    "is_affix"  => 0,
                    "methods"   => "GET",
                    "is_frame"  => null,
                ],
                [
                    "app"       => "admin",
                    "title"     => "状态",
                    "code"      => "dev:gateway_blacklist:status",
                    "level"     => null,
                    "type"      => 3,
                    "sort"      => 999,
                    "path"      => null,
                    "component" => null,
                    "redirect"  => null,
                    "icon"      => null,
                    "is_show"   => 1,
                    "is_link"   => 0,
                    "link_url"  => null,
                    "enabled"   => 1,
                    "open_type" => 1,
                    "is_cache"  => 0,
                    "is_sync"   => 1,
                    "is_affix"  => 0,
                    "methods"   => "GET",
                    "is_frame"  => null,
                ],
                [
                    "app"       => "admin",
                    "title"     => "删除",
                    "code"      => "dev:gateway_blacklist:delete",
                    "level"     => null,
                    "type"      => 3,
                    "sort"      => 999,
                    "path"      => null,
                    "component" => null,
                    "redirect"  => null,
                    "icon"      => null,
                    "is_show"   => 1,
                    "is_link"   => 0,
                    "link_url"  => null,
                    "enabled"   => 1,
                    "open_type" => 1,
                    "is_cache"  => 0,
                    "is_sync"   => 1,
                    "is_affix"  => 0,
                    "methods"   => "GET",
                    "is_frame"  => null,
                ],
                [

                    "app"       => "admin",
                    "title"     => "编辑",
                    "code"      => "dev:gateway_blacklist:edit",
                    "level"     => null,
                    "type"      => 3,
                    "sort"      => 999,
                    "path"      => null,
                    "component" => null,
                    "redirect"  => null,
                    "icon"      => null,
                    "is_show"   => 1,
                    "is_link"   => 0,
                    "link_url"  => null,
                    "enabled"   => 1,
                    "open_type" => 1,
                    "is_cache"  => 0,
                    "is_sync"   => 1,
                    "is_affix"  => 0,
                    "methods"   => "GET",
                    "is_frame"  => null,
                ],
            ],
        ],
    ],
],
//            [
//                "app"       => "admin",
//                "title"     => "在线开发",
//                "code"      => "dev:online",
//                "level"     => null,
//                "type"      => 1,
//                "sort"      => 999,
//                "path"      => "/dev/online",
//                "component" => null,
//                "redirect"  => null,
//                "icon"      => "material-symbols:home-work-outline-rounded",
//                "is_show"   => 1,
//                "is_link"   => 0,
//                "link_url"  => null,
//                "enabled"   => 0,
//                "open_type" => 1,
//                "is_cache"  => 0,
//                "is_sync"   => 1,
//                "is_affix"  => 0,
//                "methods"   => "GET",
//                "is_frame"  => null,
//            ],
        ],
    ],
    [
        "app"       => "admin",
        "title"     => "人工智能",
        "code"      => "ai",
        "level"     => null,
        "type"      => 1,
        "sort"      => 999,
        "path"      => "/ai",
        "component" => null,
        "redirect"  => null,
        "icon"      => "carbon:ai-recommend",
        "is_show"   => 1,
        "is_link"   => 0,
        "link_url"  => null,
        "enabled"   => 1,
        "open_type" => 1,
        "is_cache"  => 0,
        "is_sync"   => 1,
        "is_affix"  => 0,
        "methods"   => "GET",
        "is_frame"  => null,
        "children"  => [
            [
                "app"       => "admin",
                "title"     => "智能问答",
                "code"      => "ai:chat",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999,
                "path"      => "/ai/agent",
                "component" => "/ai/agent/index",
                "redirect"  => null,
                "icon"      => "mingcute:kakao-talk-line",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 1,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
            ],
        ],
    ],
    [
        "app"       => "admin",
        "title"     => "系统设置",
        "code"      => "system",
        "level"     => null,
        "type"      => 1,
        "sort"      => 1000,
        "path"      => "/system",
        "component" => "BasicLayout",
        "redirect"  => "",
        "icon"      => "ant-design:setting-outlined",
        "is_show"   => 1,
        "is_link"   => 0,
        "link_url"  => null,
        "enabled"   => 1,
        "open_type" => 0,
        "is_cache"  => 1,
        "is_sync"   => 1,
        "is_affix"  => 0,
        "methods"   => "GET",
        "is_frame"  => null,
        "children"  => [
            [
                "app"       => "admin",
                "title"     => "附件管理",
                "code"      => "system:files",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999,
                "path"      => "/system/files",
                "component" => "/system/files/index",
                "redirect"  => null,
                "icon"      => "ant-design:folder-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:files:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "下载",
                        "code"      => "system:files:download",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
            [
                "app"       => "admin",
                "title"     => "通知公告",
                "code"      => "system:notice",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999,
                "path"      => "/system/notice",
                "component" => "/system/notice/index",
                "redirect"  => null,
                "icon"      => "ant-design:comment-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 1,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "编辑",
                        "code"      => "system:notice:edit",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:notice:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "新增",
                        "code"      => "system:notice:create",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
            [
                "app"       => "admin",
                "title"     => "菜单管理",
                "code"      => "system:menu",
                "level"     => null,
                "type"      => 2,
                "sort"      => 1000,
                "path"      => "/system/menu",
                "component" => "/system/menu/index",
                "redirect"  => null,
                "icon"      => "ant-design:menu-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "新增",
                        "code"      => "system:menu:create",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 10,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:menu:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 20,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "编辑",
                        "code"      => "system:menu:edit",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 30,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
            [
                "app"       => "admin",
                "title"     => "部门管理",
                "code"      => "system:dept",
                "level"     => null,
                "type"      => 2,
                "sort"      => 1000,
                "path"      => "/system/dept",
                "component" => "/system/dept/index",
                "redirect"  => null,
                "icon"      => "ant-design:facebook-filled",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "新增",
                        "code"      => "system:dept:create",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 10,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:dept:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 20,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "编辑",
                        "code"      => "system:dept:edit",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 30,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,

                    ],
                ],
            ],
            [
                "app"       => "admin",
                "title"     => "职位管理",
                "code"      => "system:post",
                "level"     => null,
                "type"      => 2,
                "sort"      => 1000,
                "path"      => "/system/post",
                "component" => "/system/post/index",
                "redirect"  => null,
                "icon"      => "ant-design:database-filled",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "添加",
                        "code"      => "system:post:create",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 10,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:post:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 20,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "编辑",
                        "code"      => "system:post:edit",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 30,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
            [
                "app"       => "admin",
                "title"     => "用户管理",
                "code"      => "system:user",
                "level"     => null,
                "type"      => 2,
                "sort"      => 1000,
                "path"      => "/system/user",
                "component" => "/system/user/index",
                "redirect"  => null,
                "icon"      => "ant-design:user-add-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "添加",
                        "code"      => "system:user:create",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 10,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:user:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 20,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "编辑",
                        "code"      => "system:user:edit",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 30,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "重置密码",
                        "code"      => "system:user:reset_password",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 50,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "冻结用户",
                        "code"      => "system:user:locked",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 70,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "取消冻结",
                        "code"      => "system:user:un_locked",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 80,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
            [
                "app"       => "admin",
                "title"     => "角色管理",
                "code"      => "system:role",
                "level"     => null,
                "type"      => 2,
                "sort"      => 1000,
                "path"      => "/system/role",
                "component" => "/system/role/index",
                "redirect"  => null,
                "icon"      => "ant-design:team-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "新增",
                        "code"      => "system:role:create",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 10,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:role:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 20,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "编辑",
                        "code"      => "system:rbac:edit",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 50,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "分配用户",
                        "code"      => "system:role:user",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 60,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "添加用户",
                        "code"      => "system:auth:user_role",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "移除用户",
                        "code"      => "system:auth:remove_user_role",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
            [
                "app"       => "admin",
                "title"     => "数据字典",
                "code"      => "system:dict",
                "level"     => null,
                "type"      => 2,
                "sort"      => 1000,
                "path"      => "/system/dict",
                "component" => "/system/dict/index",
                "redirect"  => null,
                "icon"      => "ant-design:profile-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "新增",
                        "code"      => "system:dict:create",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 10,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:dict:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 20,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "编辑",
                        "code"      => "system:dict:edit",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 30,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "枚举字典",
                        "code"      => "system:dict:enum",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 40,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,

                    ],
                    [
                        "app"       => "admin",
                        "title"     => "字典项列表",
                        "code"      => "system:dict_item:list",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 50,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "字典项添加",
                        "code"      => "system:dict_item:create",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 60,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "字典项删除",
                        "code"      => "system:dict_item:delete",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 70,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "字典项编辑",
                        "code"      => "system:dict_item:edit",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 80,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
            [
                "app"       => "admin",
                "title"     => "系统参数",
                "code"      => "system:config",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999999,
                "path"      => "/systen/config",
                "component" => "/system/config/index",
                "redirect"  => null,
                "icon"      => "ant-design:tool-outlined",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
            ],
            [
                "app"       => "admin",
                "title"     => "数据回收",
                "code"      => "system:recycle_bin",
                "level"     => null,
                "type"      => 2,
                "sort"      => 999999999,
                "path"      => "/system/recycle-bin",
                "component" => "/system/recycle-bin/index",
                "redirect"  => null,
                "icon"      => "ant-design:rest-filled",
                "is_show"   => 1,
                "is_link"   => 0,
                "link_url"  => null,
                "enabled"   => 1,
                "open_type" => 0,
                "is_cache"  => 0,
                "is_sync"   => 1,
                "is_affix"  => 0,
                "methods"   => "GET",
                "is_frame"  => null,
                "children"  => [
                    [
                        "app"       => "admin",
                        "title"     => "详情",
                        "code"      => "system:recycle_bin:detail",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                    [
                        "app"       => "admin",
                        "title"     => "恢复",
                        "code"      => "system:recycle_bin:recover",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 1,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,

                    ],
                    [
                        "app"       => "admin",
                        "title"     => "删除",
                        "code"      => "system:recycle_bin:remove",
                        "level"     => null,
                        "type"      => 3,
                        "sort"      => 999,
                        "path"      => null,
                        "component" => null,
                        "redirect"  => null,
                        "icon"      => null,
                        "is_show"   => 1,
                        "is_link"   => 0,
                        "link_url"  => null,
                        "enabled"   => 1,
                        "open_type" => 0,
                        "is_cache"  => 0,
                        "is_sync"   => 1,
                        "is_affix"  => 0,
                        "methods"   => "GET",
                        "is_frame"  => null,
                    ],
                ],
            ],
        ],
    ],
];
